import argparse
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import time
import json

# Regex pattern to identify valid email addresses
EMAIL_REGEX = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

# Keywords to prioritize HR emails over generic info emails
HR_KEYWORDS = ['bewerbung', 'personal', 'karriere', 'hr']

def scrape_emails_from_website(base_url):
    print(f"🔍 Scanning: {base_url}")
    found_emails = set()
    
    # Common subpages where German clinics hide their application emails
    pages_to_check = [
        f"{base_url}/impressum"
    ]

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    for page in pages_to_check:
        try:
            response = requests.get(page, headers=headers, timeout=10)
            # Only proceed if the page actually exists
            if response.status_code == 200:
                # Extract text from the HTML
                soup = BeautifulSoup(response.text, 'html.parser')
                text = soup.get_text()
                
                # Find all email matches using Regex
                emails_on_page = re.findall(EMAIL_REGEX, text)
                
                for email in emails_on_page:
                    email_clean = email.lower()
                    # Filter out common junk emails or image file names that look like emails
                    if not email_clean.endswith(('.png', '.jpg', '.jpeg', '.gif', '.sentry')):
                        found_emails.add(email_clean)
            
            # Be polite to their servers
            time.sleep(1) 
            
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Could not access {page}: {e}")
            continue

    return list(found_emails)

def select_best_email(email_list):
    """Prioritizes 'Bewerbung' or 'Personal' emails over generic 'info' emails."""
    if not email_list:
        return None
        
    for email in email_list:
        if any(keyword in email for keyword in HR_KEYWORDS):
            return email # Return the first HR-specific email found
            
    return email_list[0] # Fallback to the first email found if no HR email exists

def main():
    parser = argparse.ArgumentParser(description="Scrape clinic websites for recruiter email addresses.")
    parser.add_argument("--input", default="found_clinics_sachsen.xlsx", help="Excel file generated by clinic_finder (default: found_clinics_sachsen.xlsx)")
    parser.add_argument("--city", help="Optional city/region label to store in the output workbook.")
    parser.add_argument("--limit", type=int, help="Optional cap on number of clinics to process.")
    args = parser.parse_args()

    print("🤖 Reading target clinics from Excel...")
    try:
        df_in = pd.read_excel(args.input)
        if args.limit:
            df_in = df_in.head(args.limit)
        target_clinics = df_in.to_dict('records')
    except Exception as e:
        print(f"Error loading Excel: {e}")
        df_in = pd.DataFrame()
        target_clinics = []

    results = []
    if args.city:
        region_label = args.city
    elif target_clinics and "City" in df_in.columns:
        region_label = str(df_in["City"].iat[0])
    else:
        region_label = ""

    for idx, clinic in enumerate(target_clinics):
        try:
            with open("live_status.json", "w", encoding="utf-8") as f:
                json.dump({
                    "status": "Scraping",
                    "current": idx + 1,
                    "total": len(target_clinics),
                    "clinic": clinic["Clinic Name"],
                    "message": f"Scanning {clinic['Clinic Name']}...",
                    "found_emails": len(results)
                }, f)
        except Exception:
            pass

        all_emails = scrape_emails_from_website(clinic["URL"])
        best_email = select_best_email(all_emails)
        
        if best_email:
            print(f"✅ Found target email for {clinic['Clinic Name']}: {best_email}")
            results.append({
                "Clinic Name": clinic["Clinic Name"],
                "Email": best_email,
                "Contact Person": clinic.get("Contact Person", "Sehr geehrte Damen und Herren"),
                "City": region_label or clinic.get("City", "")
            })
            pd.DataFrame(results).to_excel("scraped_leads_live.xlsx", index=False)
        else:
            print(f"❌ No emails found for {clinic['Clinic Name']}")

    if results:
        df = pd.DataFrame(results)
        df.to_excel("scraped_leads.xlsx", index=False)
        print("\n🎉 Scraping complete! Saved to scraped_leads.xlsx")
        print("You can now rename this file to 'input.xlsx' to feed it directly into your application bot!")
        
        try:
            with open("live_status.json", "w", encoding="utf-8") as f:
                json.dump({
                    "status": "Finished Scraping",
                    "message": f"Scraping complete! Extracted {len(results)} valid emails.",
                    "found_emails": len(results),
                    "current": len(target_clinics),
                    "total": len(target_clinics)
                }, f)
        except Exception:
            pass
    else:
        print("No emails harvested. Check the input URLs and try again.")


if __name__ == "__main__":
    main()
